### PR TITLE
Fix expanding template expressions from defaultDestination for CLI install 

### LINKED ISSUE #821: defaultDestination's [Name] [Version] expansion no longer works for LibMan CLI
This no longer works for LibMan CLI

_Originally posted by @dunnodepends in https://github.com/aspnet/LibraryManager/issues/759#issuecomment-3721782542_

### PR DESCRIPTION
**Pull request by jimmylewis**
Apply the same expansion when installing libraries whether the manifest is from disk or generated in memory.  (CLI updates the manifest on disk after the install succeeds.)

Some extras:
- turned off preference for var when the type is apparent.  Since we don't use var through the majority of the code, this was distracting.
- Added a workaround for running the CLI integration tests when a workaround is in place for #728.  Apparently if a parent directory's nuget.config configures packageSourceMappings, there isn't a way to turn it off in a child directory's nuget.config.

Resolves #821

### CODE REVIEW

File: src/LibraryManager/Utilities/PathTemplateUtility.cs [hunk 1]
```diff
@@ -0,0 +1,37 @@
+﻿// Licensed to the .NET Foundation under one or more agreements.
+// The .NET Foundation licenses this file to you under the MIT license.
+
+using System.Diagnostics.CodeAnalysis;
+using System.Linq;
```
Comment (dbreshears) [inline src/LibraryManager/Utilities/PathTemplateUtility.cs:5]: Looks like this can be removed

**Review by dbreshears — APPROVED** [review]

File: src/LibraryManager/Utilities/PathTemplateUtility.cs (hunk 1 above)
Comment (jimmylewis) [reply src/LibraryManager/Utilities/PathTemplateUtility.cs:5]: Needed for net481 (for string.Contains(char))
