### PR TITLE
Fix CLI install via unpkg

### LINKED ISSUE #157: [CLI][unpkg]: libman install jquery -p unpkg fails
### Minimal repro steps
*What is the smallest, simplest set of steps to reproduce the issue. If needed, provide a project that demonstrates the issue.*  
run `libman install jquery -p unpkg -d lib/unpkg/jquery` 

### Expected result
*What would you expect to happen if there wasn't a bug*  
jquery with the latest version is installed. 

### Actual result
*What is actually happening*  
Installation fails with the error: 
```
libman install jquery -p unpkg -d lib/unpkg/jquery
Microsoft.Web.LibraryManager.Contracts.ResourceDownloadException: Failed to download resource from "http://unpkg.com/jquery@/AUTHORS.txt"
   at Microsoft.Web.LibraryManager.WebRequestHandler.GetStreamAsync(String url, CancellationToken cancellationToken) in D:\git\LibraryManager\src\LibraryManager\CacheService\WebRequestHandler.cs:line 35
   at Microsoft.Web.LibraryManager.CacheService.DownloadToFileAsync(String url, String fileName, CancellationToken cancellationToken) in D:\git\LibraryManager\src\LibraryManager\CacheService\CacheService.cs:line 62
   at Microsoft.Web.LibraryManager.CacheService.RefreshCacheAsync(IEnumerable`1 librariesCacheMetadata, CancellationToken cancellationToken) in D:\git\LibraryManager\src\LibraryManager\CacheService\CacheService.cs:line 97
   at Microsoft.Web.LibraryManager.Providers.Unpkg.UnpkgProvider.RefreshCacheAsync(ILibraryInstallationState state, CancellationToken cancellationToken) in D:\git\LibraryManager\src\LibraryManager\Providers\Unpkg\UnpkgProvider.cs:line 117
Failed to install library "jquery"
[LIB010]: Failed to download resource from "http://unpkg.com/jquery@/AUTHORS.txt"
```

### PR DESCRIPTION
**Pull request by prafullbhosale**
Fixes #157 

- Makes unpkg and cdnjs providers consistent:
  - `GetLatestVersion()` now returns only the version part for both cdnjs and unpkg
  - `Catalog.GetLibraryIds()` now returns the full libraryIds for unpkg
- FileSystem provider returns empty string for `GetLatestVersion()`
- `UpdateSuggestedActionSet` combines the library's `displayname` and `latestVersion` to show the update suggestion.

### CODE REVIEW

File: src/LibraryManager/Providers/Unpkg/UnpkgLibraryGroup.cs [hunk 1]
```diff
@@ -24,7 +25,9 @@ public UnpkgLibraryGroup(string displayName, string description = null)
 
             if (npmPackageInfo != null)
             {
-                return npmPackageInfo.Versions.Select(semanticVersion => semanticVersion.ToString()).ToArray();
+                return npmPackageInfo.Versions
```
Comment (jodavis) [inline src/LibraryManager/Providers/Unpkg/UnpkgLibraryGroup.cs]: We should at ToList() to this Linq, so that it captures a snapshot of the results.

File: src/LibraryManager.Vsix/Json/SuggestedActions/UpdateSuggestedActionSet.cs [hunk 2]
```diff
@@ -76,14 +77,16 @@ public override bool HasActionSets
         {
             var list = new List<ISuggestedAction>();
 
-            string latestStable = await catalog.GetLatestVersion(_provider.InstallationState.LibraryId, false, cancellationToken).ConfigureAwait(false);
+            string latestStable = LibraryNamingScheme.Instance.GetLibraryId(_provider.InstallationState.Name,
+                            await catalog.GetLatestVersion(_provider.InstallationState.LibraryId, false, cancellationToken).ConfigureAwait(false));
 
             if (!string.IsNullOrEmpty(latestStable) && latestStable != _provider.InstallationState.LibraryId)
```
Comment (jodavis) [inline src/LibraryManager.Vsix/Json/SuggestedActions/UpdateSuggestedActionSet.cs]: >latestStable [](start = 38, length = 12)

This will always be non-null and non-Empty now, because it will always contain the library name. I think it needs to check for null or empty on the version by itself. Probably the same for latestPre below.

**Comment by prafullbhosale** [comment]
:up::date: Rebased on master and address code review feedback.
