### PR TITLE
Don't write default config file during init

### LINKED ISSUE #719: Error during restore mentioning libman.config.json in use.
### Describe the bug

Error `System.IO.IOException: The process cannot access the file 'C:\Users\ericstj\.librarymanager\libman.config.json' because it is being used by another process.`  full stack below.

My best guess here is a concurrency issue with multiple projects using the same task on different nodes.  This was a clean machine that never saw this repo before, nor used LibMan at all.

```

C:\.tools\.nuget\packages\microsoft.web.librarymanager.build\2.1.175\build\Microsoft.Web.LibraryManager.Build.targets(35,9): error MSB4018: The "Microsoft.Web.LibraryManager.Build.RestoreTask" task failed unexpectedly. [C:\src\dotnet\eshoponcontainers\src\Services\Identity\Identity.API\Identity.API.csproj]
C:\.tools\.nuget\packages\microsoft.web.librarymanager.build\2.1.175\build\Microsoft.Web.LibraryManager.Build.targets(35,9): error MSB4018: System.TypeInitializationException: The type initializer for 'Microsoft.Web.LibraryManager.Cache.WebRequestHandler' threw an exception. [C:\src\dotnet\eshoponcontainers\src\Services\Identity\Identity.API\Identity.API.csproj]
C:\.tools\.nuget\packages\microsoft.web.librarymanager.build\2.1.175\build\Microsoft.Web.LibraryManager.Build.targets(35,9): error MSB4018:  ---> System.TypeInitializationException: The type initializer for 'Microsoft.Web.LibraryManager.Configuration.Settings' threw an exception. [C:\src\dotnet\eshoponcontainers\src\Services\Identity\Identity.API\Identity.API.csproj]
C:\.tools\.nuget\packages\microsoft.web.librarymanager.build\2.1.175\build\Microsoft.Web.LibraryManager.Build.targets(35,9): error MSB4018:  ---> System.IO.IOException: The process cannot access the file 'C:\Users\ericstj\.librarymanager\libman.config.json' because it is being used by another process. [C:\src\dotnet\eshoponcontainers\src\Services\Identity\Identity.API\Identity.API.csproj]
C:\.tools\.nuget\packages\microsoft.web.librarymanager.build\2.1.175\build\Microsoft.Web.LibraryManager.Build.targets(35,9): error MSB4018:    at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options) [C:\src\dotnet\eshoponcontainers\src\Services\Identity\Identity.API\Identity.API.csproj]
C:\.tools\.nuget\packages\microsoft.web.librarymanager.build\2.1.175\build\Microsoft.Web.LibraryManager.Build.targets(35,9): error MSB4018:    at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode) [C:\src\dotnet\eshoponcontainers\src\Services\Identity\Identity.API\Identity.API.csproj]
C:\.tools\.nuget\packages\microsoft.web.librarymanager.build\2.1.175\build\Microsoft.Web.LibraryManager.Build.targets(35,9): error MSB4018:    at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode) [C:\src\dotnet\eshoponcontainers\src\Services\Identity\Identity.API\Identity.API.csproj]
C:\.tools\.nuget\packages\microsoft.web.librarymanager.build\2.1.175\build\Microsoft.Web.LibraryManager.Build.targets(35,9): error MSB4018:    at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode) [C:\src\dotnet\eshoponcontainers\src\Services\Identity\Identity.API\Identity.API.csproj]
C:\.tools\.nuget\packages\microsoft.web.librarymanager.build\2.1.175\build\Microsoft.Web.LibraryManager.Build.targets(35,9): error MSB4018:    at System.IO.StreamReader.ValidateArgsAndOpenPath(String path, Encoding encoding, Int32 bufferSize) [C:\src\dotnet\eshoponcontainers\src\Services\Identity\Identity.API\Identity.API.csproj]
C:\.tools\.nuget\packages\microsoft.web.librarymanager.build\2.1.175\build\Microsoft.Web.LibraryManager.Build.targets(35,9): error MSB4018:    at System.IO.StreamReader..ctor(String path) [C:\src\dotnet\eshoponcontainers\src\Services\Identity\Identity.API\Identity.API.csproj]
C:\.tools\.nuget\packages\microsoft.web.librarymanager.build\2.1.175\build\Microsoft.Web.LibraryManager.Build.targets(35,9): error MSB4018:    at Microsoft.Web.LibraryManager.Configuration.Settings..ctor() [C:\src\dotnet\eshoponcontainers\src\Services\Identity\Identity.API\Identity.API.csproj]
C:\.tools\.nuget\packages\microsoft.web.librarymanager.build\2.1.175\build\Microsoft.Web.LibraryManager.Build.targets(35,9): error MSB4018:    at Microsoft.Web.LibraryManager.Configuration.Settings..cctor() [C:\src\dotnet\eshoponcontainers\src\Services\Identity\Identity.API\Identity.API.csproj]
C:\.tools\.nuget\packages\microsoft.web.librarymanager.build\2.1.175\build\Microsoft.Web.LibraryManager.Build.targets(35,9): error MSB4018:    --- End of inner exception stack trace --- [C:\src\dotnet\eshoponcontainers\src\Services\Identity\Identity.API\Identity.API.csproj]
C:\.tools\.nuget\packages\microsoft.web.librarymanager.build\2.1.175\build\Microsoft.Web.LibraryManager.Build.targets(35,9): error MSB4018:    at Microsoft.Web.LibraryManager.Configuration.Settings.get_DefaultSettings() [C:\src\dotnet\eshoponcontainers\src\Services\Identity\Identity.API\Identity.API.csproj]
C:\.tools\.nuget\packages\microsoft.web.librarymanager.build\2.1.175\build\Microsoft.Web.LibraryManager.Build.targets(35,9): error MSB4018:    at Microsoft.Web.LibraryManager.Configuration.ProxySettings.get_Default() [C:\src\dotnet\eshoponcontainers\src\Services\Identity\Identity.API\Identity.API.csproj]
C:\.tools\.nuget\packages\microsoft.web.librarymanager.build\2.1.175\build\Microsoft.Web.LibraryManager.Build.targets(35,9): error MSB4018:    at Microsoft.Web.LibraryManager.Cache.WebRequestHandler..cctor() [C:\src\dotnet\eshoponcontainers\src\Services\Identity\Identity.API\Identity.API.csproj]
C:\.tools\.nuget\packages\microsoft.web.librarymanager.build\2.1.175\build\Microsoft.Web.LibraryManager.Build.targets(35,9): error MSB4018:    --- End of inner exception stack trace --- [C:\src\dotnet\eshoponcontainers\src\Services\Identity\Identity.API\Identity.API.csproj]
C:\.tools\.nuget\packages\microsoft.web.librarymanager.build\2.1.175\build\Microsoft.Web.LibraryManager.Build.targets(35,9): error MSB4018:    at Microsoft.Web.LibraryManager.Cache.WebRequestHandler.get_Instance() [C:\src\dotnet\eshoponcontainers\src\Services\Identity\Identity.API\Identity.API.csproj]
C:\.tools\.nuget\packages\microsoft.web.librarymanager.build\2.1.175\build\Microsoft.Web.LibraryManager.Build.targets(35,9): error MSB4018:    at Microsoft.Web.LibraryManager.Build.Contracts.Dependencies.Initialize() [C:\src\dotnet\eshoponcontainers\src\Services\Identity\Identity.API\Identity.API.csproj]
C:\.tools\.nuget\packages\microsoft.web.librarymanager.build\2.1.175\build\Microsoft.Web.LibraryManager.Build.targets(35,9): error MSB4018:    at Microsoft.Web.LibraryManager.Build.Contracts.Dependencies..ctor(IHostInteraction hostInteraction, IEnumerable`1 assemblyPaths) [C:\src\dotnet\eshoponcontainers\src\Services\Identity\Identity.API\Identity.API.csproj]
C:\.tools\.nuget\packages\microsoft.web.librarymanager.build\2.1.175\build\Microsoft.Web.LibraryManager.Build.targets(35,9): error MSB4018:    at Microsoft.Web.LibraryManager.Build.Contracts.Dependencies.FromTask(String workingDirectory,IEnumerable`1 assemblyPaths) [C:\src\dotnet\eshoponcontainers\src\Services\Identity\Identity.API\Identity.API.csproj]
C:\.tools\.nuget\packages\microsoft.web.librarymanager.build\2.1.175\build\Microsoft.Web.LibraryManager.Build.targets(35,9): error MSB4018:    at Microsoft.Web.LibraryManager.Build.RestoreTask.Execute() [C:\src\dotnet\eshoponcontainers\src\Services\Identity\Identity.API\Identity.API.csproj]
C:\.tools\.nuget\packages\microsoft.web.librarymanager.build\2.1.175\build\Microsoft.Web.LibraryManager.Build.targets(35,9): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute() [C:\src\dotnet\eshoponcontainers\src\Services\Identity\Identity.API\Identity.API.csproj]
C:\.tools\.nuget\packages\microsoft.web.librarymanager.build\2.1.175\build\Microsoft.Web.LibraryManager.Build.targets(35,9): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask(ITaskExecutionHost taskExecutionHost, TaskLoggingContext taskLoggingContext, TaskHost taskHost, ItemBucket bucket, TaskExecutionMode howToExecuteTask)[C:\src\dotnet\eshoponcontainers\src\Services\Identity\Identity.API\Identity.API.csproj]
C:\.tools\.nuget\packages\microsoft.web.librarymanager.build\2.1.175\build\Microsoft.Web.LibraryManager.Build.targets(35,9): error MSB4018: The "Microsoft.Web.LibraryManager.Build.RestoreTask" task failed unexpectedly. [C:\src\dotnet\eshoponcontainers\src\Web\WebStatus\WebStatus.csproj]
C:\.tools\.nuget\packages\microsoft.web.librarymanager.build\2.1.175\build\Microsoft.Web.LibraryManager.Build.targets(35,9): error MSB4018: System.TypeInitializationException: The type initializer for 'Microsoft.Web.LibraryManager.Cache.WebRequestHandler' threw an exception. [C:\src\dotnet\eshoponcontainers\src\Web\WebStatus\WebStatus.csproj]
C:\.tools\.nuget\packages\microsoft.web.librarymanager.build\2.1.175\build\Microsoft.Web.LibraryManager.Build.targets(35,9): error MSB4018:  ---> System.TypeInitializationException: The type initializer for 'Microsoft.Web.LibraryManager.Configuration.Settings' threw an exception. [C:\src\dotnet\eshoponcontainers\src\Web\WebStatus\WebStatus.csproj]
C:\.tools\.nuget\packages\microsoft.web.librarymanager.build\2.1.175\build\Microsoft.Web.LibraryManager.Build.targets(35,9): error MSB4018:  ---> System.IO.IOException: The process cannot access the file 'C:\Users\ericstj\.librarymanager\libman.config.json' because it is being used by another process. [C:\src\dotnet\eshoponcontainers\src\Web\WebStatus\WebStatus.csproj]
C:\.tools\.nuget\packages\microsoft.web.librarymanager.build\2.1.175\build\Microsoft.Web.LibraryManager.Build.targets(35,9): error MSB4018:    at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options) [C:\src\dotnet\eshoponcontainers\src\Web\WebStatus\WebStatus.csproj]
C:\.tools\.nuget\packages\microsoft.web.librarymanager.build\2.1.175\build\Microsoft.Web.LibraryManager.Build.targets(35,9): error MSB4018:    at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode) [C:\src\dotnet\eshoponcontainers\src\Web\WebStatus\WebStatus.csproj]
C:\.tools\.nuget\packages\microsoft.web.librarymanager.build\2.1.175\build\Microsoft.Web.LibraryManager.Build.targets(35,9): error MSB4018:    at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode) [C:\src\dotnet\eshoponcontainers\src\Web\WebStatus\WebStatus.csproj]
C:\.tools\.nuget\packages\microsoft.web.librarymanager.build\2.1.175\build\Microsoft.Web.LibraryManager.Build.targets(35,9): error MSB4018:    at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode) [C:\src\dotnet\eshoponcontainers\src\Web\WebStatus\WebStatus.csproj]
C:\.tools\.nuget\packages\microsoft.web.librarymanager.build\2.1.175\build\Microsoft.Web.LibraryManager.Build.targets(35,9): error MSB4018:    at System.IO.StreamReader.ValidateArgsAndOpenPath(String path, Encoding encoding, Int32 bufferSize) [C:\src\dotnet\eshoponcontainers\src\Web\WebStatus\WebStatus.csproj]
C:\.tools\.nuget\packages\microsoft.web.librarymanager.build\2.1.175\build\Microsoft.Web.LibraryManager.Build.targets(35,9): error MSB4018:    at System.IO.StreamReader..ctor(String path) [C:\src\dotnet\eshoponcontainers\src\Web\WebStatus\WebStatus.csproj]
C:\.tools\.nuget\packages\microsoft.web.librarymanager.build\2.1.175\build\Microsoft.Web.LibraryManager.Build.targets(35,9): error MSB4018:    at Microsoft.Web.LibraryManager.Configuration.Settings..ctor() [C:\src\dotnet\eshoponcontainers\src\Web\WebStatus\WebStatus.csproj]
C:\.tools\.nuget\packages\microsoft.web.librarymanager.build\2.1.175\build\Microsoft.Web.LibraryManager.Build.targets(35,9): error MSB4018:    at Microsoft.Web.LibraryManager.Configuration.Settings..cctor() [C:\src\dotnet\eshoponcontainers\src\Web\WebStatus\WebStatus.csproj]
C:\.tools\.nuget\packages\microsoft.web.librarymanager.build\2.1.175\build\Microsoft.Web.LibraryManager.Build.targets(35,9): error MSB4018:    --- End of inner exception stack trace --- [C:\src\dotnet\eshoponcontainers\src\Web\WebStatus\WebStatus.csproj]
C:\.tools\.nuget\packages\microsoft.web.librarymanager.build\2.1.175\build\Microsoft.Web.LibraryManager.Build.targets(35,9): error MSB4018:    at Microsoft.Web.LibraryManager.Configuration.Settings.get_DefaultSettings() [C:\src\dotnet\eshoponcontainers\src\Web\WebStatus\WebStatus.csproj]
C:\.tools\.nuget\packages\microsoft.web.librarymanager.build\2.1.175\build\Microsoft.Web.LibraryManager.Build.targets(35,9): error MSB4018:    at Microsoft.Web.LibraryManager.Configuration.ProxySettings.get_Default() [C:\src\dotnet\eshoponcontainers\src\Web\WebStatus\WebStatus.csproj]
C:\.tools\.nuget\packages\microsoft.web.librarymanager.build\2.1.175\build\Microsoft.Web.LibraryManager.Build.targets(35,9): error MSB4018:    at Microsoft.Web.LibraryManager.Cache.WebRequestHandler..cctor() [C:\src\dotnet\eshoponcontainers\src\Web\WebStatus\WebStatus.csproj]
C:\.tools\.nuget\packages\microsoft.web.librarymanager.build\2.1.175\build\Microsoft.Web.LibraryManager.Build.targets(35,9): error MSB4018:    --- End of inner exception stack trace --- [C:\src\dotnet\eshoponcontainers\src\Web\WebStatus\WebStatus.csproj]
C:\.tools\.nuget\packages\microsoft.web.librarymanager.build\2.1.175\build\Microsoft.Web.LibraryManager.Build.targets(35,9): error MSB4018:    at Microsoft.Web.LibraryManager.Cache.WebRequestHandler.get_Instance() [C:\src\dotnet\eshoponcontainers\src\Web\WebStatus\WebStatus.csproj]
C:\.tools\.nuget\packages\microsoft.web.librarymanager.build\2.1.175\build\Microsoft.Web.LibraryManager.Build.targets(35,9): error MSB4018:    at Microsoft.Web.LibraryManager.Build.Contracts.Dependencies.Initialize() [C:\src\dotnet\eshoponcontainers\src\Web\WebStatus\WebStatus.csproj]
C:\.tools\.nuget\packages\microsoft.web.librarymanager.build\2.1.175\build\Microsoft.Web.LibraryManager.Build.targets(35,9): error MSB4018:    at Microsoft.Web.LibraryManager.Build.Contracts.Dependencies..ctor(IHostInteraction hostInteraction, IEnumerable`1 assemblyPaths) [C:\src\dotnet\eshoponcontainers\src\Web\WebStatus\WebStatus.csproj]
C:\.tools\.nuget\packages\microsoft.web.librarymanager.build\2.1.175\build\Microsoft.Web.LibraryManager.Build.targets(35,9): error MSB4018:    at Microsoft.Web.LibraryManager.Build.Contracts.Dependencies.FromTask(String workingDirectory,IEnumerable`1 assemblyPaths) [C:\src\dotnet\eshoponcontainers\src\Web\WebStatus\WebStatus.csproj]
C:\.tools\.nuget\packages\microsoft.web.librarymanager.build\2.1.175\build\Microsoft.Web.LibraryManager.Build.targets(35,9): error MSB4018:    at Microsoft.Web.LibraryManager.Build.RestoreTask.Execute() [C:\src\dotnet\eshoponcontainers\src\Web\WebStatus\WebStatus.csproj]
C:\.tools\.nuget\packages\microsoft.web.librarymanager.build\2.1.175\build\Microsoft.Web.LibraryManager.Build.targets(35,9): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute() [C:\src\dotnet\eshoponcontainers\src\Web\WebStatus\WebStatus.csproj]
C:\.tools\.nuget\packages\microsoft.web.librarymanager.build\2.1.175\build\Microsoft.Web.LibraryManager.Build.targets(35,9): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask(ITaskExecutionHost taskExecutionHost, TaskLoggingContext taskLoggingContext, TaskHost taskHost, ItemBucket bucket, TaskExecutionMode howToExecuteTask)[C:\src\dotnet\eshoponcontainers\src\Web\WebStatus\WebStatus.csproj]
```

### To Reproduce
I cloned and tried to build https://github.com/dotnet-architecture/eshoponcontainers on a new machine.

### Expected behavior
Restore completes successfully.

### Additional context
Building with `dotnet build` of the root sln in eshop.  Using 8.0 RC2 dotnet

### PR DESCRIPTION
**Pull request by jimmylewis**
Per #719, this can cause file lock issues with multiple concurrent processes executing (for example, parallel MSBuild nodes in a solution).  Retrospectively, it doesn't provide anything useful either.  It's faster to just create the defaults in memory than to get file IO involved.

Resolves #719

### CODE REVIEW

File: src/LibraryManager/Configuration/Settings.cs [hunk 1]
```diff
@@ -64,24 +64,18 @@ protected Settings()
...
-                    // If there were any errors, we'll reset the file
+                    // If there were any errors, we'll take the defaults
+                    // TODO: log a warning
                 }
             }
 
             if (_rootObject is null)
             {
-                InitSettingsFile(ConfigFilePath);
+                _rootObject = new JObject(new JProperty("config", new JObject()));
```
Comment (alexgav) [inline src/LibraryManager/Configuration/Settings.cs:74]: I know it's not the part you are changing, but what do you think of adding a couple of retries for reading the existing file before giving up and going to the empty defaults? If it's for stuff like proxy configuration, it seems like existing data is pretty important :) Not sure why we decided to overwrite with empty file on first failure to begin with.

File: src/LibraryManager/Configuration/Settings.cs [hunk 2]
```diff
@@ -64,24 +64,18 @@ protected Settings()
                 }
                 catch (JsonReaderException)
                 {
-                    // If there were any errors, we'll reset the file
+                    // If there were any errors, we'll take the defaults
+                    // TODO: log a warning
```
Comment (alexgav) [inline src/LibraryManager/Configuration/Settings.cs:68]: Definitely would be nice, at least dump it to the JSON output window via ILanguageHost?

**Review by alexgav — APPROVED** [review]
LGTM overall, a couple of suggestions

File: src/LibraryManager/Configuration/Settings.cs (hunk 2 above)
Comment (jimmylewis) [reply src/LibraryManager/Configuration/Settings.cs:68]: That only would help if it's installed by VS, but for most users it's either through the CLI or the MSBuild tasks (even building in VS, the build happens out of proc). The only times we install packages within VS are via the wizard (1st time, since it's not reentrant) or via save-on-edit in libman.config.

We need better logging in general, it's nearly impossible to diagnose most of the failures reported without getting a debugger (and a consistent repro) involved.

File: src/LibraryManager/Configuration/Settings.cs (hunk 1 above)
Comment (jimmylewis) [reply src/LibraryManager/Configuration/Settings.cs:74]: The original idea was that if the file is corrupted (e.g. invalid JSON), then we'd fall back to the defaults (and reset the file).    Retries won't fix a file that doesn't exist or isn't parseable JSON.  For this issue, the problem was caused by a lingering write lock.  We could retry until that lock is released, but the only time writes occur to the file outside of this (now-removed) reset was by using the CLI (`libman config ...`) or manually editing the file.  Neither of these is likely to overlap with a restore operation in a separate process to cause the same issue.
